before_script:
  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ##
  - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ## Add Host Keys
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  
stages: 
    - deploy
  
prod_deploy:
  stage: deploy
  script:
    - echo "Deploy to webserver"
    - rsync -av ./ krodgit@129.27.218.247:/test/ --exclude-from=exclude --delete
  allow_failure: false
  environment:
    name: deploy
  only:
  - master
  tags:
    - Sisyphus
  when: always
